[build]
  # No build command needed for static HTML/CSS/JS
  command = ""

  # Publish from the root directory
  publish = "."

# Headers for better caching and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/CursedTimerUlil-Aznm.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
